### ISSUE TITLE
integrate Nicolo's jet tagging

### ISSUE THREAD

**Issue by cbernet** [HEP-FCC/heppy#48]
Hi friends, 

I've started the integration of Nicolò's jet tagging system in heppy, on this branch: 
https://github.com/cbernet/heppy/tree/btag_nicolo

It is working, you can just go take this heppy branch, and run the ZH hadronic analysis to get this new btagging model:
https://github.com/cbernet/heppy/blob/btag_nicolo/test/analysis_ee_ZH_had_cfg.py

The b tagging is set up after this line:
https://github.com/cbernet/heppy/blob/btag_nicolo/test/analysis_ee_ZH_had_cfg.py#L193
You can change this flag to go back to the old b tagging parametrization.

Please note that the interface has changed a bit. We now have a single script to run heppy, either in interactive or batch mode: 
- interactive : 'heppy -i analysis_ee_ZH_had_cfg.py'
- batch : 'heppy OutDir analysis_ee_ZH_had_cfg.py'

I will now do a bit of code refactoring for a better integration of these tools, like e.g. splitting the IP smearing code and the btagging code, so that other b tagging algorithms can be used with the smeared impact parameters. 

@kbehr, please let us know how it goes with your tests. 
Also, don't hesitate to contact me on skype if you encounter any problem in the migration to the new version of heppy (or the new version of the FCC software).

Thanks a lot to @nfoppiani for all this nice work! 

Colin

@alicerobson @pjanot

**Comment by cbernet** [comment]
Here is the mail sent by @pjanot summarizing all the information from @nfoppiani

Hi Alice and Colin, 

This morning I had a chat with Nicolò and could gather all the information we wanted about his work on b tagging during his stay as a Summer Student last July-August.

1) The method he coded (as a module in HEPPY) is based on the b-tagging method employed in ALEPH, described in this note:


2) The actual implementation and summary of his work is described in his summer student report

http://cds.cern.ch/record/2222396?ln=it

where the definition of track impact parameter that he took is that of Fig. 3.1 rather than that of 3.2 (as originally used in ALEPH).

3) It is also summarised in the slides of the talk he gave in the CMG group meeting

https://indico.cern.ch/event/548909/

but there is really nothing new with respect to the report. 

4) The code of the HEPPY python module is in Github: https://github.com/nfoppiani/heppy/blob/top-mass-measurement/analyzers/ImpactParameterJetTag.py.
     The two impact parameters definitions are available in this code https://github.com/nfoppiani/heppy/blob/top-mass-measurement/analyzers/ImpactParameterJetTag.py#L190, 
      and he used the "simple" one (that of Fig. 3.10 
 
 
5) the definitions of the various track smearing he used are in Github too: https://github.com/nfoppiani/heppy/blob/top-mass-measurement/sequences/JetsSequence.py#L42

6) IMPORTANT: For the module to give the expected results, the thickness of the beam pipe that was introduced by Colin and his master student to explore another way for the b tagging (which simulates another track smearing) has to be turned to 0 (or more easily, the radiation length of the beam pipe material was assigned a very large number by Nicolò). 


It is clear that some tuning will be in order, but I think it is an extremely advanced starting point already. I would not advise to restart the code from scratch, as the experience gained by Nicolò would be lost forever. Instead, Nicolò is going to be at CERN from next Monday onwards until the end of the month, and discussions with him could take place to benefit from the subtleties he may have learned last summer. I would anyway first recommend Alice to read the report from Nicolò, and ask me whatever questions she would like to ask, before starting to modify the code. 

Cheers, 

Patrick.

**Comment by nfoppiani** [comment]
Hello everybody,

I am really happy that my code is going to be integrated in the actual version of heppy!

I think that the mail from @pjanot summarizes already all the information needed, but let me add a few more words.

I have not found any parametrization of the IP resolution in CMS, for this reason I have only written the resolutions for ALEPH and for ILD, but the good thing is that you can add your custom resolution just by writing down a python function.

Concerning the MVA part: basically the code computes the probability that the jet is compatible with the primary vertex, and this could one of a few discriminating variables between a b and a light jet. So in the very end of my summer student I started to compute more variables to give to a very simple MVA algorithm that I wrote from scratch (and in the end a BDT or a NN should work by far better), and I am not even sure that the integration between the MVA and the module ImpactParamterJetTag is working...

If any help is needed in understanding, re-writing or fixing something, I will be happy to contribute. I will be at CERN starting from May 15th (unfortunately I changed my plan) but you can always reach me on skype if needed.
 
Furthermore, I had a nice discussion with Andrea Rizzi about new ideas for the btag we can implement in the fast simulation...maybe it could be interesting to discuss about this in order to further this b-tag fast sim work.

Cheers
Nicolò

**Comment by cbernet** [comment]
I did not manage to reproduce the ALEPH results with this technique, and I don't see how the CMS results could be parametrized in this way (due to the large amount of tracker material in CMS).
-> closing for now.
